# Generated by Django 6.0.3 on 2026-03-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={"ordering": ["module", "order"]},
        ),
        migrations.RemoveField(
            model_name="problem",
            name="original_url",
        ),
        migrations.AddField(
            model_name="problem",
            name="test_cases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of dicts: [{'input': '...', 'output': '...'}]",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.CharField(
                choices=[("EASY", "Easy"), ("MEDIUM", "Medium"), ("HARD", "Hard")],
                default="MEDIUM",
                max_length=20,
            ),
        ),
    ]
