# Generated by Django 4.2.7 on 2026-03-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_problem_hints_alter_module_id_alter_problem_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="hints",
        ),
    ]
