# Generated by Django 4.2.7 on 2026-03-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_remove_problem_hints"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="constraints",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="problem",
            name="hidden_tests",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="problem",
            name="input_format",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="output_format",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="sample_tests",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="problem",
            name="test_cases",
            field=models.JSONField(
                blank=True, default=list, help_text="Combined for backend execution"
            ),
        ),
    ]
