# Generated by Django 4.2.7 on 2026-03-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0006_choice_question_quiz_quizattempt_questionresponse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="time_limit",
            field=models.IntegerField(default=30, help_text="Time limit in minutes"),
        ),
    ]
