# Generated by Django 4.2.7 on 2026-03-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0007_quiz_time_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionresponse",
            name="is_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questionresponse",
            name="reviewer_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_REVIEW", "Pending Review"),
                    ("COMPLETED", "Completed"),
                ],
                default="COMPLETED",
                max_length=20,
            ),
        ),
    ]
