# Generated by Django 4.2.7 on 2026-03-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0008_questionresponse_is_reviewed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="random_seed",
            field=models.IntegerField(
                default=0, help_text="Seed for consistent MCQ randomization"
            ),
        ),
    ]
